const { notice, noticeDelete, noticeCreate, educationCategories, educationDelete, educationCreate, videos, videoDelete, videoCreate, feedback } = require("../controllers/adminControllers");
const router = require("express").Router();
router.post(process.env.REACT_APP_BASE_URL + "/notice", notice);
router.post(process.env.REACT_APP_BASE_URL + "/notice/delete", noticeDelete);
router.post(process.env.REACT_APP_BASE_URL + "/notice/create", noticeCreate);
router.post(process.env.REACT_APP_BASE_URL + "/education", educationCategories);
router.post(process.env.REACT_APP_BASE_URL + "/education/delete", educationDelete);
router.post(process.env.REACT_APP_BASE_URL + "/education/create", educationCreate);
router.post(process.env.REACT_APP_BASE_URL + "/education/videos", videos);
router.post(process.env.REACT_APP_BASE_URL + "/education/videos/delete", videoDelete);
router.post(process.env.REACT_APP_BASE_URL + "/education/videos/create", videoCreate);
router.get(process.env.REACT_APP_BASE_URL + "/feedback", feedback);
module.exports = router;